### ISSUE TITLE
eqio__trigger elements create horizontal scrollbars

### ISSUE THREAD

**Issue by mwinkelm** [stowball/eqio#4]
Hi Matt,

I really like the simple approach to have something like container/element queries. While trying to adapt your approach to an Angular directive I realized that the trigger elements (`.eqio__trigger`) generate a horizontal scrollbar when the width doesn't fit into viewport anymore. As this element may only be visually hidden to make the IntersectionObserver working, the whole idea seems to be limited to some use cases.

![eqio](https://user-images.githubusercontent.com/6881829/65035707-2569aa80-d94a-11e9-86fd-6d49249454a1.png)

Did you use eqio yourself in mobile first projects to build components that self adapt to their parents width?

Thanks,
Markus

**Comment by stowball** [comment]
Hi Markus

Sorry, I completely missed that you logged this issue.

I guess I've never experienced this for 2 reasons:

1. I primarily develop on Mac, which doesn't have visible scrollbars by default; and
2. I always have `body { overflow-x: hidden; }` in my reset stylesheet to prevent any elements accidentally causing horizontal scroll.

I will update the docs accordingly to mention that *some parent* needs to have its `overflow-x` `hidden`.

Thanks!
